server:  
  port: ${PORT:2222}

spring:  
  application:
    name: person-service
  datasource:
    url: jdbc:oracle:thin:@//oraasgtd10-scan.nam.nsroot.net:8888/REGTAXD
    username: CMRTID
    password: Ie67w9P4
    driver_class_name: oracle.jdbc.OracleDriver
  jpa:
    database_platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        cache:
          hazelcast:
            use_native_client: true
            native_client_address: 127.0.0.1
            native_client_group: dev
            native_client_password: dev
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory